name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Setup Gem Files
      run: |
        bundle install --jobs 4 --retry 3 # Install berks gem
     - name: Run Code Analysis using cookstyle
      run: |
        echo `pwd`
        echo "\n"
        chmod +x sca.sh
        ./sca.sh
    - name: Build and Bundle Cookbooks and dependencies
      run: |
        echo `pwd`
        echo "\n"
        chmod +x berks-vendor.sh
        echo `ls -l`

        ./berks-vendor.sh # Berks vendor cookbooks
